language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.9"
before_script:
  - npm install -g gulp
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage